### ISSUE TITLE
Internal Server Error after Clicking Check-out

### ISSUE THREAD

**Issue by psteyn** [arkhitech/redmine_leaves#70]
Hi there,

It seems there is an incompatibility or bug related to Ruby 2.2.2 and Redmine 2.6.6.stable.

Steps to reproduce:

1.  Check in
2.  Check out (and be presented with a page to log your time)
3.  Log time, and click on 'add'

Full error in log:

  ESC[1mESC[36mUserTimeCheck Load (0.2ms)ESC[0m  ESC[1mSELECT `user_time_checks`.* FROM `user_time_checks` WHERE (user_id = 164 and check_out_time IS NOT NULL) ORDER BY id DESC LIMIT 1ESC[0m
Completed 500 Internal Server Error in 40.8ms

NoMethodError (undefined method `check_in_time' for nil:NilClass):
  plugins/redmine_leaves/app/controllers/user_time_checks_controller.rb:345:in `create_time_entries'
  actionpack (3.2.22) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.22) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.22) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.22) lib/active_support/callbacks.rb:480:in `_run__1412554644337452762__process_action__1829444038329409751__callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.22) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.22) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.22) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.22) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.22) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.22) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'

**Comment by psteyn** [comment]
BTW, this is in current master
